[cli] Add `sanity init --bare` flag
sanity-io/sanity pull request #1989
Opened 2020-08-31 07:31 UTC by rexxars

**Type of change (check at least one)**

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  Documentation (fix or update to documentation)
- [ ]  Maintenance
- [ ]  Other, please describe:

**Does this change require a documentation update? (Check one)**

- [x]  Yes
- [ ]  No

**Description**

This PR allows a user to run `sanity init --bare` and only create a project and (optionally) a dataset. If the user chooses to, it will also create a folder with a `sanity.json` (containing project ID and dataset) and a `package.json` (containing `@sanity/core` as a dependency).

I didn't want to create even more "branches" in the init project code which is already a bit unwieldy, so I separated some logic into their own files for reuse between the "init bare" method and the "regular" init.

**Note for release**

Add `--bare` flag to CLI `sanity init` command, for cases where a studio is not needed.

**Checklist** 

- [x]  I have read the [Contributing Guidelines](https://github.com/sanity-io/sanity/blob/next/CONTRIBUTING.md)
- [ ]  The PR title includes a link to the relevant issue
- [x]  The PR title is appropriately formatted: `[some-package] PR title (#123)`
- [x]  The code is linted
- [x]  The test suite is passing
- [ ]  Corresponding changes to the documentation have been made

2020-08-31 10:59 UTC, kmelve requested changes
This is awesome! A couple of suggestions for wordings only

2020-08-31 10:59 UTC, kmelve commented on packages/@sanity/cli/src/commands/init/initCommand.js
> +  --bare Do not create any studio files, only sanity.json/package.json
```suggestion
  --bare Create a project without a studio, only sanity.json and package.json
```

2020-08-31 10:59 UTC, kmelve commented on packages/@sanity/cli/src/commands/init/initCommand.js
> +  # Initialize a "bare" project, only creating sanity.json and package.json
```suggestion
  # Initialize a project without Sanity Studio, only creating sanity.json and package.json
```

2020-09-02 07:39 UTC, kmelve approved these changes

2020-10-13 11:02 UTC, vicbergquist approved these changes
LGTM!

2022-08-11 06:38 UTC, rexxars commented
Will revisit this later.

2022-08-11 06:38 UTC, closed without merging