fix(form-builder): enforce that DateInput value is constrained to timeStep
sanity-io/sanity pull request #2628
Opened 2021-07-21 10:28 UTC by sgulseth

### Description

If a datetime is configured with `timeStep=60` the user is not able to select minutes because there's only one option `00` and onSelect doesn't trigger on a "non-change". This PR adds an effect that ensures that the value for date time minutes are compatible with the configured `timeStep`-value

### What to review

### Notes for release

Enforce that DateInput value is constrained to timeStep

2021-07-22 08:15 UTC, rexxars requested changes
The time logic seems right to me, but the fact that it runs as an effect on render seems off to me, since it leads to inconsistent behavior:

- For the default time step behavior, you can open the date/calendar selector without any side effects. Until you click a specific date or change the time, no value is set for the field
- For a field with specific time steps, if you open a date/calendar selector, the field will automatically set it's value to the closest time matching the time step

Maybe this logic needs to be applied at a lower level, eg in the change handler or some such? What do you think, @bjoerge ?

2021-07-22 08:15 UTC, rexxars commented on packages/@sanity/form-builder/src/inputs/DateInputs/base/calendar/Calendar.tsx
> +  useEffect(() => {
Could we add a comment explaining in rough terms what this `useEffect` call is intended to handle? It's not obvious to me reading the code

2021-07-22 10:04 UTC, sgulseth commented on packages/@sanity/form-builder/src/inputs/DateInputs/DateTimeInput.tsx
> +    [parsedOptions, onChange]
Ah, yes, makes sense. Updating

2021-07-23 09:33 UTC, rexxars approved these changes
👍

2021-07-23 09:41 UTC, bjoerge approved these changes
LGTM 👍🏼

2021-07-23 11:29 UTC, merged