fix(desk-tool): fix ui and performance issues in timeline
sanity-io/sanity pull request #2883
Opened 2021-10-20 17:08 UTC by hermanwikner

### Description

This PR adds UI and performance improvements to the timeline.

- Render items in a `VirtualList` to prevent app from freezing when there is a lot of data to display
- Improve 'scroll-to-load-more'
- Update the styling of different states / interactions
- General updates to improve performance such as memoization

### What to review

### Notes for release

2021-11-02 10:25 UTC, RitaDias commented on packages/@sanity/desk-tool/src/panes/document/timeline/__workshop__/TimelineItemStory.tsx
> +import {Card, Container, Flex, LayerProvider, Menu} from '@sanity/ui'
What's our stance on adding things to the workshop and push them to next? Should we keep it as a dev tool or keep it as well and push it to next? 🤔

2021-11-02 10:41 UTC, RitaDias requested changes
Really good job 👏 I've added just a couple of questions and suggestion so just have a look ✨

2021-11-02 10:41 UTC, RitaDias commented on packages/@sanity/desk-tool/src/panes/document/timeline/timelineItem.styled.tsx
> +        --card-fg-color: ${theme.sanity.color.selectable?.primary.selected.fg};
This colour seems to be used a lot all the way down 👇 maybe it makes sense to just extract it to a const above all of this and be called in each of these properties instead?

like
`const selectedColor = theme.sanity.color.selectable?.primary.selected.fg`
(and so on with the other that might be repeated)

and then here you'd just `--card-fg-color: ${selectedColor};`

2021-11-02 10:41 UTC, RitaDias commented on packages/@sanity/desk-tool/src/panes/document/timeline/timelineItem.styled.tsx
> +    &:not([disabled], [data-selected]) {
I know that the names tend to be pretty direct and straightforward but I'd suggest adding comments to the top of these sections explaining what they are

2021-11-02 10:41 UTC, RitaDias commented on packages/@sanity/desk-tool/src/panes/document/timeline/timelineItem.styled.tsx
> +    content: '';
Does this need the `content` when it's not a pseudo-element? 🤔

2021-11-02 10:41 UTC, RitaDias commented on packages/@sanity/desk-tool/src/panes/document/timeline/timelineMenu.tsx
> +  useGlobalKeyDown((e) => {
nice 😚 👌

2021-11-02 10:41 UTC, RitaDias commented on packages/@sanity/desk-tool/src/panes/document/timeline/types.ts
> +export type TimelineItemState = 'enabled' | 'disabled' | 'withinSelection' | 'active'
Why, is it just about clarifying the name? 🤔

2021-11-02 10:42 UTC, RitaDias commented on packages/@sanity/desk-tool/src/panes/document/timeline/userAvatarStack.tsx
> +        <AvatarCard key={userId}>
Just out of pure curiosity, why was it needed to add this?

2021-11-17 12:59 UTC, mariuslundgard commented
@hermanwikner – can you setup a workshop that shows the problems with using `VirtualList` and other aspects that remain to be sorted out?

2022-04-05 11:29 UTC, closed without merging