feat: info level validation messages
sanity-io/sanity pull request #2960
Opened 2021-11-26 14:35 UTC by hermanwikner

### Description

### What to review

### Notes for release

2021-12-03 11:10 UTC, vicbergquist approved these changes
great work!

2021-12-03 11:11 UTC, vicbergquist commented
Can we add some examples of this in the validation schema?

2021-12-06 12:59 UTC, rexxars requested changes
Nice work!
Would be good if we could add a test case or two in the test studio. Maybe we could also add a few test cases for error/warning/info level messages?

2021-12-07 11:02 UTC, hermanwikner commented on packages/@sanity/base/src/components/formField/FormFieldValidationStatus.tsx
> +  }, [])
Thank you! 👍 Will fix

2021-12-07 11:07 UTC, hermanwikner commented
> Can we add some examples of this in the validation schema?

Yes, good idea @vicbergquist  👍

2021-12-07 22:34 UTC, ricokahler approved these changes
it's perfect

2021-12-08 09:02 UTC, merged