feat(desk-tool): update `MissingDocumentTypesMessage` design
sanity-io/sanity pull request #3110
Opened 2022-01-28 09:45 UTC by hermanwikner

### Description

This PR updates the design of the `MissingDocumentTypesMessage` that is displayed if the schema is empty.

Before/after:

<img width="1169" alt="Screenshot 2022-01-28 at 10 40 40" src="https://user-images.githubusercontent.com/15094168/151523823-08577840-a9d2-4ba6-b7bd-e5ef866e228f.png">

**How to make this screen render:**

Remove the schema part in `sanity.json`:

```
{
  "name": "part:@sanity/base/schema",
  "path": "schema"
}
```

Return empty array in `createSchema`:

```
export default createSchema({
  name: 'test-examples',
  types: schemaTypes.concat([]),
})
```

### What to review

- Review the design

### Notes for release

Update design on empty schema message

2022-01-28 10:24 UTC, mikolajdobrucki requested changes

2022-01-28 10:24 UTC, mikolajdobrucki commented on packages/@sanity/desk-tool/src/components/MissingDocumentTypesMessage.tsx
> +              Read more about how to add schema typesa
typo in last word "typesa"

2022-01-28 11:03 UTC, hermanwikner commented on packages/@sanity/desk-tool/src/components/MissingDocumentTypesMessage.tsx
> +              Read more about how to add schema typesa
Thanks! 👍

2022-02-01 10:05 UTC, sjelfull approved these changes
Looks good to merge, unless Design Department has any objections

2022-02-01 10:17 UTC, merged