feat: notifications
sanity-io/sanity pull request #3139
Opened 2022-02-08 17:23 UTC by hermanwikner

### Description

### What to review

### Notes for release

2022-03-08 07:11 UTC, rexxars requested changes
Great work! A few minor typing requests from my end, but otherwise good!

2022-03-08 07:11 UTC, rexxars commented on packages/@sanity/base/src/module-status/types.ts
> +  description: any
We should probably type this, as it is quite hard to reason about the shape without knowing what is in it?

Rough untested sketch based on what I can tell from the shape:
```ts
import type {SanityImageHotspot, SanityImageCrop, SanityImageDimensions} from '@sanity/asset-utils'
import type {PortableTextBlock} from '@portabletext/types' // Remember to add this one as a dependency!

interface CodeBlock {
  _type: 'code'
  code?: string
  language?: string
  filename?: string
  highlightedLines?: number[]
}

interface MaterializedImage {
  _type: 'image'
  alt?: string
  caption?: string
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  asset?: {
    _id: string
    path: string
    metadata: {
      dimensions: SanityImageDimensions
      lqip?: string
    }
  }
}

type StudioBlockContent = 
  | PortableTextBlock
  | CodeBlock
  | MaterializedImage
```

2022-03-08 07:11 UTC, rexxars commented on packages/@sanity/default-layout/src/update/PortableTextContent/PortableTextContent.tsx
> +  value: any
If we add typings for the block content shape we should make sure this one is also typed correctly

2022-03-08 07:11 UTC, rexxars commented on packages/@sanity/default-layout/src/update/PortableTextContent/PortableTextContent.tsx
> +function Image({value}) {
...and if typed, we'd get the right type here - `MaterializedImage` (or whatever we want to call it)

2022-03-08 09:34 UTC, hermanwikner commented on packages/@sanity/base/src/module-status/types.ts
> +export interface ChangeItem {
Yes, good idea to make it clearer what "change" this type is referring to 👍

2022-03-08 14:41 UTC, rexxars approved these changes
👍

2022-03-11 13:57 UTC, mariuslundgard approved these changes
Looks amazing – great work @hermanwikner.

One thing we should adjust before merging:
If the API returns no changelog items, but the Studio is outdated, we should still show the update status dialog:
![image](https://user-images.githubusercontent.com/406933/157881515-9f46d9a2-bb87-454d-aef5-2147fb35d656.png)

2022-03-15 16:51 UTC, merged