fix(desk-tool): add full timestamp tooltip to timeline items
sanity-io/sanity pull request #3628
Opened 2022-09-12 10:26 UTC by sjelfull

### Description

This adds the full change timestamp to a tooltip when you hover over the relative time stamp in the version timeline.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/10508/189631357-324894d1-f647-44a9-b60d-8aad7d21de84.png">

### What to review

- Is this the best UI solution?

### Notes for release

- Added full timestamp to version timeline

2022-09-12 14:21 UTC, rexxars commented
Supersedes https://github.com/sanity-io/sanity/pull/3251?

2022-09-12 14:27 UTC, sjelfull commented
> Supersedes #3251?

Correct, this is more aligned with how we show timestamps elsewhere. Will update the #3251.

2022-09-13 08:26 UTC, RitaDias requested changes
Small comment for structure but everything else looks good ✨

2022-09-13 08:26 UTC, RitaDias commented on packages/@sanity/desk-tool/src/panes/document/timeline/timelineItem.tsx
> +const TimestampBox = styled(Box)`
Move this to the styled file in ln10 :)

2023-01-17 23:04 UTC, robinpyon commented
Thanks @sjelfull, sorry this was stuck in limbo. This been ported to V3 with a few minor tweaks in #4100

2023-01-17 23:04 UTC, closed without merging