fix: direct link to add cors origin
sanity-io/sanity pull request #3755
Opened 2022-10-13 09:43 UTC by stipsan

### Description

Simplifies the CORS error dialog to reduce technical language, and adds a "Add origin" CTA that takes you to a [new flow in manage](https://github.com/sanity-io/manage/pull/291). The new flow prefills the CORS information for you and gives the user a "Confirm" CTA at the end. Pressing it closes the popup window.
Upon return a `winow.onfocus` handler automatically retries.

This means that the happy path for resolving a CORS problem becomes:
1. User sees the CORS error dialog, and clicks on CTA.
2. A new window opens in manage, explaining what is about to happen, and the user clicks "Confirm".
3. The origin is added and the window closes, and the Studio loads automatically.

### What to review

Try the flow on origins we don't allow: `cd dev/test-studio && yarn sanity:dev --port 3030`.
You should see the error, clicking on "Add origin" should let you do so, and show an error message in Manage if you don't have admin rights.

Live test link: https://test-studio-no-cors.vercel.app/

### Notes for release

2022-10-21 11:04 UTC, hermanwikner approved these changes
This was a really smooth experience – great work! ✨ 

This is ready to be merged, but I have a small suggestion for a design update.

What I have changed:

- Update the `radius` on `TextInput`
- Include a link to our CORS origin documentation
- Moved the button to the dialog's `footer` as well as updating the button's copy and adding an icon indicating that a new window will open

<img width="1622" alt="Screen Shot 2022-10-21 at 13 02 30" src="https://user-images.githubusercontent.com/15094168/197181343-1b77265f-94ff-4535-bda5-778bfc2f8d7c.png">

2022-10-21 11:08 UTC, sjelfull requested changes
A few small changes requested - looks good otherwise!

2022-10-21 11:08 UTC, sjelfull commented on packages/sanity/src/core/studio/screens/CorsOriginErrorScreen.tsx
>            <Text>
```suggestion
          <Text as="p">
```

2022-10-21 11:08 UTC, sjelfull commented on packages/sanity/src/core/studio/screens/CorsOriginErrorScreen.tsx
> +          <TextInput value={origin} readOnly />
This input should have a (visually hidden) label

2022-10-21 13:58 UTC, hermanwikner approved these changes

2022-10-23 19:08 UTC, merged

2022-10-23 19:10 UTC, stipsan commented
Will apply fixes in a follow-up commit. @hermanwikner do you mind sharing your feedback with the others [on the related Figma?](https://www.figma.com/file/C77wPdW97bGo7Of1vMAc80/V3-Starters-%E2%80%93-Prototypes?node-id=102%3A1089) :relaxed: