feat(template): v3-ize get-started template
sanity-io/sanity pull request #4225
Opened 2023-02-28 21:21 UTC by svirs

### Description

Updated get-started template to use studio v3 and typescript

### What to review

Initializing template creates a studio with no errors, c&p snippet works:
`npm create sanity@latest -- --template get-started --create-project "Sanity Project" --dataset production`

### Notes for release

Update get-started template to v3

2023-02-28 21:35 UTC, rexxars requested changes

2023-02-28 21:49 UTC, svirs commented on packages/@sanity/cli/src/actions/init-project/templates/getStarted.ts
> +  dataset: 'asdf',
👍 Whoop, forgot to undo that!

2023-03-01 04:13 UTC, rexxars commented
@svirs I did a few consistency changes, namely using named exports over default exports. Also added a missing `@sanity/icons` dependency, and noticed we are missing `@types/react` from the default dependencies we install - so added that too - even if it's slightly unrelated to this PR. With this, I think this looks good to go from my perspective.

2023-03-01 04:13 UTC, rexxars approved these changes

2023-03-01 04:28 UTC, merged