fix(core): add virtualization to array of objects and references
sanity-io/sanity pull request #4299
Opened 2023-03-21 16:42 UTC by binoy14

### Description

Adds virtualization to Array of Objects which helps fix performance issues when dealing with large arrays

### What to review

- If the virtualization logic make sense
- ~Is boundary component implemented correctly?~ Confirmed with Marius, usage is fine
- I tested different scenarios including drag and drop, custom height components and there was no issue

### Notes for release

- Fixes performance issues when dealing with large arrays

2023-04-11 19:50 UTC, rexxars requested changes
There seems to be a bug when you open an array item, close it, and try to scroll:

https://user-images.githubusercontent.com/48200/231273011-a2454a9d-7bfb-4fb2-a14e-8abb47a3f591.mov

2023-04-11 21:39 UTC, binoy14 commented
My last commit should fix the issue mentioned. The reason the issue happens is when you open an item and close it, it does not set the focusPath to nothing 

https://github.com/sanity-io/sanity/blob/11c5efb044838dbb5f1f3de32a64def11c8e3ee5/packages/sanity/src/core/form/members/array/items/ArrayOfObjectsItem.tsx#L208

My question is should the focus reset when the modal is closed? I am not sure what side effects it would have.

2023-04-12 14:26 UTC, binoy14 commented on packages/sanity/src/desk/panes/document/documentPanel/DocumentPanel.tsx
> +  const documentScrollElement = useRef<HTMLDivElement>(null)
I changed it for some reason 😅 but I don't think it makes a difference I tested it with state and it works as expected, I'll revert this change

2023-04-12 14:26 UTC, binoy14 commented on packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
> +  const documentPanelRef = useBoundaryElement()
sure I can rename

2023-04-12 18:19 UTC, binoy14 commented on packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
>    const memberKeys = useMemo(() => members.map((member) => member.key), [members])
Should be fixed in latest rebase. Let me know if you mean something else

2023-04-12 18:19 UTC, binoy14 commented on packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
> +              }}
As per our conversation, since this changes on scroll there would not be a lot of benefits memoizing this

2023-04-12 18:38 UTC, binoy14 commented on packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
> +                }}
same as above this changes on scroll so memo is useless here

2023-04-12 18:44 UTC, binoy14 commented on packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
> +  const observeElementOffset = useCallback<
The cleanup function probably is used for removing the event listeners it mimics what the library does 

https://github.com/TanStack/virtual/blob/beta/packages/virtual-core/src/index.ts#L138-L140

2023-04-14 13:53 UTC, bjoerge approved these changes
Fantastic work @binoy14! This is good to merge from my side now ✨

2023-04-14 16:19 UTC, rexxars approved these changes
Great work!

2023-04-18 15:20 UTC, merged