feat: document list search
sanity-io/sanity pull request #4436
Opened 2023-04-28 07:09 UTC by hermanwikner

### Description

### What to review

### Notes for release

2023-05-05 14:18 UTC, bjoerge requested changes
Great work!

I pushed a suggestion on how to improve the document list query here: https://github.com/sanity-io/sanity/commit/c3983111d423ed2c29837b7cd2461953fe3e34c0

During testing I also found that the error handling/retry logic isn't working (try e.g. blocking the listener request in devtools, and you'll see that the document list loads forever)

2023-05-10 15:59 UTC, robinpyon commented on packages/sanity/src/desk/panes/documentList/useDocumentList.ts
> +  const isLoading =
Really minor – a clarifying comment here would be great

i.e. why is `isLoading = true` when `Boolean(loading && result === null && !error)`? Logically I'd assume that `isLoading` would be true even when `loading` is true, even with a `null` result. Perhaps I'm getting thrown off by the variable name itself.

Additionally – is `isInitialLoading` still being used?

2023-05-10 16:03 UTC, robinpyon approved these changes
Really great work @hermanwikner! Will defer to @bjoerge on `listenSearchQuery` (though we also spoke about this offline).

2023-05-11 13:55 UTC, mikolajdobrucki approved these changes
Looks amazing! So much work that went into. I'm so excited we're finally making it! 🔥🔥🔥

2023-05-11 13:57 UTC, merged