fix(form): set focus according to focus path on inputs inside block objects
sanity-io/sanity pull request #4457
Opened 2023-05-04 11:57 UTC by bjoerge

### Description

Currently, if you follow a deep link to a block object field (opened in a dialog) it doesn't put focus on it, but rather sets focus on the first field inside the dialog ([repro](https://test-studio-nmx5i2a42.sanity.build/test/content/input-standard;portable-text;simpleBlock;fa801b3f-b5b6-4a9f-a310-a9f3ee45f428%2Cpath%3Dbody%255B_key%253D%253D%2522012f3404cd66%2522%255D.otherstring))

This PR removes the logic that placed focus on first field with the following logic:

If the block itself has focus (i.e. not a child of the block), we use the default behavior of Sanity UI Dialogs (which is to place focus at the first interactive element inside the dialog, e.g. the close button if the dialog has one). If a child of the block has focus (according to the current focus path), Sanity UI dialog autofocus behavior is disabled in favor of the standard focus handling of inputs/field wrappers.

### What to review
- Make sure deep linking to fields and inputs inside blocks in portable text editor works as expected

### Notes for release
- Fixes an issue with focus placement when deep linking to fields contained in Portable Text blocks

2023-05-04 11:58 UTC, bjoerge commented on dev/test-studio/schema/standard/portableText/simpleBlock.tsx
> +    {type: 'string', name: 'otherstring', validation: (Rule) => Rule.required()},
adding a second field here provides a repro for the issue

2023-05-04 11:59 UTC, bjoerge commented on packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx
> +      focused: memberItem?.node.focused,
I'm not 100% sure about this one, the previous `focused` prop seems to come from the Portable Text editor and is based on selection. Would love to have your eyes on this @skogsmaskin.

2023-05-04 12:01 UTC, bjoerge commented on packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx
> +              blockFocused={focused}
Renamed this prop to make it clearer that it refers to whether the surrounding _block_ is having focus (can revert if it has unintended consequences)

2023-05-04 12:44 UTC, stipsan approved these changes
Code looks good 👍 I can help test this with Visual Editing if you hand me a `canary` @bjoerge 💖

2023-05-04 13:22 UTC, bjoerge commented
@stipsan released a canary @`3.10.1-canary.1+a4b0c68abe`

2023-05-09 09:01 UTC, skogsmaskin commented
Should probably merge in this first? https://github.com/sanity-io/sanity/pull/4466

2023-05-15 10:02 UTC, skogsmaskin requested changes
Will be great to have this in!

However I think we should leave the "focused" prop here as is because it's something different than the object (formstate) focus. All of these object components take `focused` prop meaning "this node is currently the focused point in the editor selection".

2023-05-24 13:58 UTC, skogsmaskin commented
Closing this one in favour to https://github.com/sanity-io/sanity/pull/4524 which includes these fixes.

2023-05-24 13:58 UTC, closed without merging