feat(core): avoid layout shift when editing title
sanity-io/sanity pull request #4828
Opened 2023-08-16 01:46 UTC by binoy14

### Description

### What to review

### Notes for release

2023-08-18 07:52 UTC, mikolajdobrucki requested changes
Agree we don't want any "layout shit" ;) 

The current CSS implementation doesn't seem to work. Please find a suggestion in my comments below.

2023-08-18 07:52 UTC, mikolajdobrucki commented on packages/sanity/src/desk/panes/document/documentPanel/documentViews/styles.ts
> +              text-overflow: ellipsis;
`text-overflow: ellipsis` won't work in this case as it only applies to single-line text elements.
Also, it won't take effect if you allow the text to wrap, over when applying `overflow:hidden`.

I would suggest to try an implementation using CSS's 'line-clamp' or just Javascript.

2023-09-12 13:35 UTC, bjoerge approved these changes
This turned out to be a very elegant solution! Great work!

2023-09-12 13:45 UTC, merged

2023-09-13 08:59 UTC, mikolajdobrucki commented
Works great! Fantastic work @binoy14! 🔥