chore(docs): adds docs for useCurrentUser hook
sanity-io/sanity pull request #4919
Opened 2023-09-12 13:53 UTC by binoy14

### Description

Adds docs for useCurrentUser hook

### What to review

This hook changes from `internal` to `public` are there any concerns about that? 

### Notes for release

N/A

2023-09-12 17:55 UTC, bjoerge approved these changes
Looks good, thanks! Would be nice if the docs report changes could be merged separately.

2023-09-12 21:57 UTC, rexxars requested changes

2023-09-12 21:57 UTC, rexxars commented on packages/sanity/src/core/store/user/hooks.ts
> + * Retrieves the current user from the source.
To third party developers, I don't think it is clear what a "source" is, and as we don't really utilize the concept for anything at the moment, I think we should steer away from using it.

```suggestion
 * Retrieves information about the currently authenticated user.
```

2023-09-13 16:29 UTC, rexxars approved these changes

2023-09-13 17:39 UTC, merged