Fix camelCase to kebab-case for resource ids
sanity-io/sanity pull request #4994
Opened 2023-10-13 18:31 UTC by jtpetty

### Description

Fixes some resource ids that were changed from camelCase to kebab-case but usages were not changed accordingly.

2023-10-13 21:42 UTC, rexxars requested changes
I spy a few more camelcased resource IDs (the locale bundle needs to be updated to match, and ideally also take a look at `dev/test-studio/plugins/locale-no-nb/bundles/desk.ts` and see if you can align those as well)

2023-10-13 21:42 UTC, rexxars commented on packages/sanity/src/desk/documentActions/DiscardChangesAction.tsx
> +  NO_CHANGES: 'action.discard-changes.disabled.noChanges',
```suggestion
  NO_CHANGES: 'action.discard-changes.disabled.no-changes',
```

2023-10-13 21:42 UTC, rexxars commented on packages/sanity/src/desk/documentActions/DiscardChangesAction.tsx
> +        message: t('action.discard-changes.confirmDialog.confirm-discard-changes'),
```suggestion
        message: t('action.discard-changes.confirm-dialog.confirm-discard-changes'),
```

2023-10-13 21:42 UTC, rexxars commented on packages/sanity/src/desk/documentActions/UnpublishAction.tsx
>    LIVE_EDIT_ENABLED: 'action.unpublish.disabled.liveEditEnabled',
```suggestion
  LIVE_EDIT_ENABLED: 'action.unpublish.disabled.live-edit-enabled',
```

2023-10-16 11:39 UTC, jtpetty commented
@rexxars - Thanks for finding the ones I missed. I think I got those now. I look at all the remaining calls to `t()` and I only see `timeAgo` as camel case. Are you fixing that in your PR?

2023-10-16 13:30 UTC, bjoerge commented
Sorry for not catching those. I was under the impression that these would trigger a compile error if they didn't match valid resource ids, but see now that that only works if you define them as a record of resource keys at usage site. Would be nice if we could find an easy way of enforcing that. Not trying to dodge blame, but this almost feels like a too easy mistake to do 😅 (and something that should be possible to catch statically?)

2023-10-16 18:54 UTC, jtpetty commented
> Sorry for not catching those. I was under the impression that these would trigger a compile error if they didn't match valid resource ids, but see now that that only works if you define them as a record of resource keys at usage site. Would be nice if we could find an easy way of enforcing that. Not trying to dodge blame, but this almost feels like a too easy mistake to do 😅 (and something that should be possible to catch statically?)

I completely agree with you. There should be some way for this to trigger an error somewhere.

2023-10-16 20:59 UTC, merged