feat(i18n): add translation for deskTool components
sanity-io/sanity pull request #5078
Opened 2023-10-26 18:15 UTC by jtpetty

### Description

Adds translation for the the components in `packages/sanity/src/desk/components/deskTool`

2023-10-31 19:32 UTC, ricokahler approved these changes

2023-11-01 20:07 UTC, rexxars requested changes

2023-11-01 20:07 UTC, rexxars commented on packages/sanity/src/desk/i18n/resources.ts
> +  /** -- DESK TOOL -- */
These are all already within the desk namespace, so do not need to be prefixed with `desk-tool`.

2023-11-01 20:07 UTC, rexxars commented on packages/sanity/src/desk/i18n/resources.ts
> +  'desk-tool.structured-error.view-doc': 'View documentation',
Structure, not structure. These are errors for when the [structure builder](https://www.sanity.io/docs/structure-builder-introduction) fails to resolve for some reason.

2023-11-02 18:11 UTC, closed without merging