Chore/move to pnpm
sanity-io/sanity pull request #5533
Opened 2024-01-21 21:57 UTC by bjoerge

### Description

### What to review

### Testing

### Notes for release

2024-01-21 22:00 UTC, bjoerge commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/sanity-io/sanity/5533?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `next`
  * **PR #5531** <a href="https://app.graphite.dev/github/pr/sanity-io/sanity/5531?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #5534** <a href="https://app.graphite.dev/github/pr/sanity-io/sanity/5534?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #5532** <a href="https://app.graphite.dev/github/pr/sanity-io/sanity/5532?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #5533** <a href="https://app.graphite.dev/github/pr/sanity-io/sanity/5533?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/sanity-io/sanity/5533?utm_source=stack-comment).

2024-02-13 20:14 UTC, stipsan approved these changes
Looks good! Added some optional suggestions 🥰

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/docReport.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/e2e-ct.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/e2e-pte.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/e2e.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/e2e.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/e2e.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/etl.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/formatCheck.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/lint-fix-if-needed.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/lint-fix-if-needed.yml
> +          body: "I ran `lint:fix --rule 'prettier/prettier: [off]'` 🧑‍💻"
```suggestion
          body: "I ran `pnpm lint:fix --rule 'prettier/prettier: [off]'` 🧑‍💻"
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/lintPr.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/perf.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/pnpm-if-needed.yml
> +      - run: pnpm dedupe
```suggestion
        run: pnpm install --config.ignore-scripts=true
      - run: pnpm dedupe --config.ignore-scripts=true
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/pr-cleanup.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/pr-cleanup.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/typeCheck.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/test.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/test.yml
> +        run: pnpm install --frozen-lockfile
```suggestion
        run: pnpm install
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/prettier-if-needed.yml
> +          body: I ran `prettier` 🧑‍💻
```suggestion
          body: I ran `pnpm prettier` 🧑‍💻
```

2024-02-13 20:14 UTC, stipsan commented on .github/workflows/prettier-if-needed.yml
> +        run: pnpm install --ignore-scripts --frozen-lockfile
```suggestion
        run: pnpm install --config.ignore-scripts=true
```

2024-02-14 16:20 UTC, binoy14 requested changes
just one change requested for handling node_modules caching besides that it looks good

2024-02-14 17:09 UTC, binoy14 approved these changes

2024-02-14 17:17 UTC, merged