feat: indicate in metadata that the quickstart option was used in project creation
sanity-io/sanity pull request #6065
Opened 2024-03-19 18:36 UTC by svirs

### Description

Project metadata.template should reflect if the --quickstart flag was used

### Testing

Project metadata should show `cli-quickstart` rather than `cli-clean` if the --quickstart flag was used for pulling down a project and its schema

2024-03-19 18:56 UTC, RostiMelk requested changes
I suggest looking into how we import/get a template here:
https://github.com/sanity-io/sanity/blob/174a61641312734ca29d57803119ca3dfad0b78e/packages/@sanity/cli/src/actions/init-project/initProject.ts#L513

If the `templateName` variable is the name that is being sent to the telemetry service, you may get around this by adding an alias "quickstart" for the "clean" template here:
https://github.com/sanity-io/sanity/blob/b14622ed44899ad6da7bb0fd1d46f56c0186a04b/packages/@sanity/cli/src/actions/init-project/templates/index.ts#L9
LIke so:
```ts
const templates: Record<string, ProjectTemplate | undefined> = {
  blog,
  clean,
  'get-started': getStartedTemplate,
  moviedb,
  shopify,
  'shopify-online-storefront': shopifyOnline,
  quickstart: clean // New alias here
}
```

2024-03-19 18:56 UTC, RostiMelk commented on packages/@sanity/cli/src/actions/init-project/initProject.ts
> +      return 'quickstart'
This is going to break as there is no template called "quickstart". 
The `--quickstart `flag relies on the "clean" template, and modifies the template with its remote schema.

2024-03-20 08:19 UTC, RostiMelk commented on packages/@sanity/cli/templates/quickstart/README.md
> +# Sanity Clean Content Studio
Should we change this title as well while we're at it?

2024-03-25 13:25 UTC, joneidejohnsen commented on packages/@sanity/cli/templates/quickstart/README.md
> +# Sanity Clean Content Studio
```suggestion
# Sanity Studio
```

2024-03-25 13:25 UTC, joneidejohnsen commented on packages/@sanity/cli/templates/quickstart/README.md
> +Congratulations, you have now installed the Sanity Content Studio, an open source real-time content editing environment connected to the Sanity backend.
```suggestion
Congratulations, you have now installed Sanity Studio, an open source real-time content editing environment connected to the Sanity Content Lake backend.
```

2024-03-25 13:26 UTC, joneidejohnsen requested changes
Suggested copy changes

2024-03-26 16:06 UTC, jtpetty approved these changes

2024-03-26 16:07 UTC, joneidejohnsen approved these changes

2024-03-26 16:07 UTC, drewlyton approved these changes

2024-03-26 16:28 UTC, merged