feat(vision): link to edit documents
sanity-io/sanity pull request #6124
Opened 2024-03-24 23:47 UTC by sgulseth

### Description

### What to review

### Testing

### Notes for release

2024-03-24 23:47 UTC, sgulseth commented
* **#6124** <a href="https://app.graphite.dev/github/pr/sanity-io/sanity/6124?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `next`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sgulseth and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-26 16:10 UTC, rexxars requested changes
Love the feature! Been wanting this for a while :) 

> Is this "safe"? Ref #6074 the user might be querying another dataset 🤔 Though it provides an easy way to inspect a document.

For both features, perhaps we should grab all workspaces and try to narrow down the workspace in question based on the dataset. If we can find a single one, then use that workspace/schema. Else do not show the link, or show it as disabled with a tooltip ("no workspace configured for this dataset"). If there are multiple workspaces that references a dataset, we can _temporarily_ show a "unable to resolve workspace for dataset", and then later expand it with a "select workspace to use"?

We'll need to expand our intent resolving, however - it currently does not allow specifying a workspace. It's something we've been wanting for other reasons though, so would make sense to add.

2024-03-26 23:01 UTC, sgulseth commented
Agree 😄  Had a look at injecting workspace into intent links, and from what I could tell it was a bigger refactor. So instead of that I pushed a change where we only render the document links if the workspace you are on matches the dataset vision is querying. Then the current behavior should work as is?

2024-12-04 23:27 UTC, rexxars approved these changes

2024-12-04 23:27 UTC, merged

2024-12-05 08:14 UTC, sgulseth commented
![image](https://github.com/user-attachments/assets/64421cc4-22a8-4fd0-87ea-df5220ceeac7)
Awesome!