fix(typegen): add placeholder group to allow typegen to show in help
sanity-io/sanity pull request #6133
Opened 2024-03-26 18:56 UTC by sgulseth

### Description

Adds missing typegen group cmd

```
» pnpm sanity help
usage: sanity [--default] [-v|--version] [-d|--debug] [-h|--help] <command> [<args>]

Commands:
   backup     Manage backups.
   build      Builds the Sanity Studio configuration into a static bundle
   codemod    Updates Sanity Studio codebase with a code modification script
   cors       Configures CORS settings for Sanity projects
   dataset    Manages datasets, like create or delete, within projects
   debug      Provides diagnostic info for Sanity Studio troubleshooting
   deploy     Builds and deploys Sanity Studio to Sanity hosting
   dev        Starts a local dev server for Sanity Studio with live reloading
   docs       Opens Sanity Studio documentation in your web browser
   documents  Manages documents in your Sanity Content Lake datasets
   exec       Executes a script within the Sanity Studio context
   graphql    Deploys changes to your project's GraphQL API(s)
   help       Displays help information about Sanity CLI commands
   hook       Sets up and manages webhooks within your Sanity project
   init       Initializes a new Sanity Studio and/or project
   install    Installs dependencies for Sanity Studio project
   login      Authenticates the CLI for access to Sanity projects
   logout     Logs out the CLI from the current user session
   manage     Opens project management interface in your web browser
   migration  Manages content migrations for Content Lake datasets
   preview    Starts a server to preview a production build of Sanity Studio
   projects   Lists all projects associated with your logged-in account
   schema     Interacts with Sanity Studio schema configurations
   start      Alias for `sanity preview`
   telemetry  Manages telemetry settings, opting in or out of data collection
   typegen    Sanity TypeGen (Beta)
   undeploy   Removes the deployed Sanity Studio from Sanity hosting
   users      Manages users of your Sanity project
   versions   Shows installed versions of Sanity Studio and components

See 'sanity help <command>' for specific information on a subcommand.
github.com/sanity-io/sanity ‹fix/typegen-cmd-group› » pnpm sanity help typegen
usage: sanity typegen [--default] [-v|--version] [-d|--debug] [-h|--help] <command> [<args>]

Commands:
   generate  Generates TypeScript types from schema types and GROQ queries

See 'sanity help typegen <command>' for specific information on a subcommand.
```

### What to review

are we missing anything else?

### Testing

can we test this? 

### Notes for release

n/a - no notes needed

2024-03-26 18:58 UTC, kmelve requested changes
Good to go with the suggestion committed :shipit:

2024-03-26 18:58 UTC, kmelve commented on packages/@sanity/cli/src/commands/typegen/typegenGroup.ts
> +  description: 'Sanity TypeGen (Beta)',
```suggestion
  description: 'Beta: Generate TypeScript types for schema and GROQ',
```

2024-03-26 19:01 UTC, kmelve approved these changes
:shipit: 
:shipit: 
:shipit: 
:shipit:

2024-03-27 17:46 UTC, rexxars approved these changes

2024-03-27 17:46 UTC, merged