fix: call dynamic hooks in a way that can be compiled
sanity-io/sanity pull request #6814
Opened 2024-05-30 15:15 UTC by stipsan

### Description

Refactors `FieldAction` and `InspectorMenuItem` components so they're no longer calling hooks that come from props. Instead, the components themselves are dynamically defined, allowing React to call said underlying hooks in a dynamic way.
It upholds the guarantee that no matter how many times, say, `FieldAction` re-renders, it'll never suddenly see `props.action.useAction()` change identity, because if it changes a new component is created instead.

### What to review

It should make sense. There's another linter warning in `DocumentInspectorMenuItemsResolver.tsx` that will be handled in a follow up.

### Testing

Existing tests should be enough.

### Notes for release

N/A

2024-05-31 08:47 UTC, bjoerge requested changes
Great! Looks like there's some unit tests/snapshots that needs updating though

2024-05-31 14:10 UTC, stipsan commented
@SocketSecurity ignore-all

2024-05-31 14:21 UTC, stipsan commented
@SocketSecurity ignore-all

2024-06-01 14:18 UTC, bjoerge approved these changes

2024-06-01 14:18 UTC, merged