fix(core): drafts not using server actions always generate a created at
sanity-io/sanity pull request #7503
Opened 2024-09-13 11:04 UTC by jordanl17

### Description
There are currently instances where (when NOT using server actions), a document would be published with a `_createdAt` of the publish time, rather than the time at which the draft was created.

This occurred due to `_createdAt` on the draft not being set on creation, thus on publish the content lake was default setting to `now`. This issue wouldn't be present if a refresh occurred between creating the draft and then publishing (since again content lake would fabricate a `createdAt` value for the draft which would then pull through in studio and be used in publish. This issue didn't occur with server actions since the server always reconciled the `createdAt` and used the local server version rather than the client memory draft.

### What to review
The issue seemingly is just that `params.timestamp` was never set on the mutation execution.

It feels most appropriate to guarantee a valid `createdAt` be defined when `create`, `createIfNotExists` or `createOrReplace` mutation are called, since these are the instances at which a draft/published doc are conceived. Even if the `timestamp` is not defined, really this should be defaulted anyway.

Do you feel this makes sense, or does it feel more appropriate to require that the caller define this, otherwise they potentially risk encountering this issue again

### Testing
* Updated `SquashedBuffer` mock for global date to validate that the `createdAt` is being set according to the default fallback the first time the draft is `createIfNotExists`

### Notes for release
Fix for an issue where published documents would be assigned a `createdAt` timestamp of their publish time, rather than the timestamp of when the associated draft was first created.

2024-09-13 14:12 UTC, bjoerge requested changes
Thanks @jordanl17! This looks like a very sensible fix to me. Left a couple of comments/suggestions. I think the isString check in particular isn't neccessary, so would be good to remove it :)

2024-09-13 14:12 UTC, bjoerge commented on packages/@sanity/mutator/test/SquashingBuffer.test.ts
> +  tx.params.timestamp = '2021-01-01T12:34:55.000Z'
Are we missing a test here for the case where tx.params.timestamp is not set?

2024-09-13 15:09 UTC, jordanl17 commented on packages/@sanity/mutator/src/document/Mutation.ts
> +      doc && isString(doc._createdAt)
I can give it a try. I added this mostly because of the type update I made to `Doc`, and I preferred to use a type guard over a type cast

2024-09-13 15:17 UTC, bjoerge commented on packages/@sanity/mutator/src/document/Mutation.ts
> +      doc && isString(doc._createdAt)
type cast should be fine in this particular case

2024-09-15 21:57 UTC, jordanl17 commented on packages/@sanity/mutator/src/document/Mutation.ts
> +      doc && isString(doc._createdAt)
Simplified this without requiring a guard or a cast

2024-09-16 16:03 UTC, bjoerge approved these changes
Excellent! Thank you for taking the time to write tests as well.

2024-09-16 16:04 UTC, merged