fix: move cliInitializedAt call higher in init flow
sanity-io/sanity pull request #7558
Opened 2024-09-30 01:07 UTC by svirs

### Description

The call to patch the `cliInitializedAt` needs to be moved above the bootstrapping of the template as it is is necessary for indicating failure cases from that function.

### Testing
Should not break anything in project init flow. (all errors from the call will continue to be caught and debug logged only)

### Notes for release
not required
-->

2024-09-30 17:41 UTC, rexxars requested changes
Can we do these in parallel? (`Promise.all()`?) Would be good to not block if the server call takes a while.

2024-10-01 01:24 UTC, svirs commented
> Can we do these in parallel? (`Promise.all()`?) Would be good to not block if the server call takes a while.

Used `Promise.allSettled` to prevent one process from aborting another

2024-10-01 10:56 UTC, drewlyton approved these changes
LGTM

2024-10-01 15:34 UTC, rexxars approved these changes

2024-10-01 15:35 UTC, merged