Fix (CLI): Do not throw an error during migrate if the project ID is passed via the --project option instead of the cli config
sanity-io/sanity pull request #7594
Opened 2024-10-04 20:17 UTC by ryanbonial

### Description

This PR sets the `apiClient`'s  `requireProject` to `false` and instead only throws an error if both the cli config and the `--project` option are missing

### What to review

### Testing

### Notes for release

2024-10-04 20:46 UTC, ryanbonial commented on packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
> +      requireProject: false,
I left this in as `false` instead of removing it so that it would indicate that `false` is intended here.

2024-10-05 14:10 UTC, rexxars requested changes

2024-10-05 14:10 UTC, rexxars commented on packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
> +    if (!project && projectConfig.projectId) {
Shouldn't this be reversed? 
```suggestion
    if (!project && !projectConfig.projectId) {
```

2024-10-05 14:18 UTC, ryanbonial commented on packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
> +    if (!project && projectConfig.projectId) {
Yes, thank you.

2024-10-05 15:11 UTC, rexxars approved these changes

2024-10-05 15:12 UTC, merged