feat(sanity): add document comparison tool
sanity-io/sanity pull request #7907
Opened 2024-11-28 16:16 UTC by juice49

### Description

This branch adds a diff view for comparing documents. Primarily, this is for use with versions, but it has been designed to support comparing any two documents.

Most of the commits are supporting work (this should probably be a stack). The main feature addition occurs in  4f030aa23991dabdda009283e9d648f18dd0baab.
#### Navigating to diff view

Users can navigate to the diff view by setting the following URL search parameters:

```
| Name               | Type                  | Required | Description                                                                                              |
|--------------------|-----------------------|----------|----------------------------------------------------------------------------------------------------------|
| `diffView`         | `'version'`           | Required | Enable *version comparison* mode UI.                                                                     |
| `previousDocument` | `${string},${string}` | Required | The document type and id identifying the *previous* document for comparison, delimited by `,` character. |
| `nextDocument`     | `${string},${string}` | Required | The document type and id identifying the *next* document for comparison, delimited by `,` character.     |
```

##### Example: specifying both `previousDocument` and `nextDocument`

```
/test/structure/author;8701af36-f4e2-4f32-b13e-fc522ddb381f?perspective=r64awNgUC&structure[diffView]=version&structure[nextDocument]=author%2Cversions.r64awNgUC.8701af36-f4e2-4f32-b13e-fc522ddb381f&structure[previousDocument]=author%2Cversions.rO2NP9B76.8701af36-f4e2-4f32-b13e-fc522ddb381f
```

### New dependency: [ScrollMirror](https://www.npmjs.com/package/scrollmirror)

I've added [ScrollMirror](https://www.npmjs.com/package/scrollmirror) to handle scroll position syncing between two panes that may have different heights. This is achieved by syncing the percentage scroll position of each pane. We could implement this directly in the Studio codebase if we wish.

### What to review

- General implementation.
- Introduction of `ScrollMirror` dependency.

### Testing

There are no tests just yet, as I've spent more time than I expected making the code render in a test environment. First, I [needed to move the diff view code](https://github.com/sanity-io/sanity/commit/2cc93c797f028cc172e11499de8fa9a0725495dc) that was originally organised as a plugin to be part of `sanity/structure`. Then I encountered many issues with existing imports in `sanity/structure` resolving to `undefined` when running in a test environment.

- Navigate to a diff view. Ensure the UI works as expected.
- Navigate to a diff view using the "Compare versions" document action. Ensure the diff view is opened as expected.

I will follow up with tests as soon as these problems are resolved.

### Notes for release

The new document comparison tool provides a side-by-side view of two different document by versions, highlighting the fields that have changed between the _previous_ and _next_ versions. Select "Compare versions" from the document actions menu when viewing any draft or version document in Studio to open the tool.

By default, the first pane displays the _previous_ version, and the second pane shows _next_ version (the version that introduces changes). Use the menu at the top of each pane to switch the versions displayed.

2025-01-14 07:51 UTC, pedrobonamin reviewed
This is fantastic, it's so great to make it possible to compare the two documents with this type of diff view. Great work! 
Added some suggestions and we are following this up in Slack.

2025-01-14 07:58 UTC, pedrobonamin commented
> Comments in diff view are not well supported, because the modal does not support document inspectors. I suggest we switch off comments in the diff view for now.
I think this is a very valid suggestion, the same could apply to the other plugins like `assist` and `translate`, I think this should not be a place where people come to edit the document and use other plugins, rather only compare them and make normal edits.

2025-01-28 22:23 UTC, juice49 commented on packages/sanity/src/core/releases/hooks/utils.ts
> +  }
Great point, thank you! Yes, I think you're right. This has now been removed.

2025-01-28 22:31 UTC, juice49 commented on packages/sanity/src/core/releases/plugin/documentActions/index.ts
> +  ]
Good catch, thanks! This is left over from a time an action was being appended here regardless of the context. Not needed anymore, so I've removed it.

2025-01-28 22:34 UTC, juice49 commented on packages/sanity/src/structure/diffView/components/DiffViewPane.tsx
> +  const version: 'draft' | 'published' | string = isDraftId(documentId)
Done, thanks! This had to be refactored a bit.

2025-01-28 22:49 UTC, juice49 commented
@pedrobonamin thanks so much for the review. I've made a few simplifications and improvements here:

- The previous document inference when navigating to the modal has been removed. It was janky because it blocked the modal rendering and messed with browser history. It was also unnecessary, because the document id stack is already known when navigating to the modal from a document action (which is how we now do it).
- The "Compare versions" document action now only appears if there is a previous version to compare with. This includes published and draft versions of the document.
- References now open in a new browser tab, rather than causing the modal to close. The previous UI was quite disorientating.
- Reference fields can no longer be used to create a new document, for the same reason as above. This is done by setting `disableNew` on all references inside the modal.

2025-01-29 16:27 UTC, pedrobonamin requested changes
This looks very good Ash, thanks for building this complex piece!
I think it's only missing to solve the error that I sent you by slack and we should find a solve for the listeners.

2025-01-30 09:35 UTC, juice49 commented on packages/sanity/src/structure/hooks/useFilteredReleases.ts
> +  // const {editState, displayed, documentType, documentId} = useDocumentPane()
Thanks!

2025-01-30 09:44 UTC, juice49 commented on packages/sanity/src/structure/diffView/components/DiffViewPane.tsx
> +// TODO: Switch off comments. Document inspectors cannot currently be shown inside the diff view.
That is interesting. It actually appears comments have stopped appearing in the comparison view anyway, thanks to some outside change. I wonder whether this is the one.

2025-03-03 16:52 UTC, bjoerge reviewed
Amazing work! My comments are mostly nits that you can feel free to disregard. The only thing I consider somewhat blocking is the use of `;` as delimited. I couldn't tell easily whether it will be properly urlencoded. If it's not encoded I think we need to change it to something else (`‚`?) It's less of an issue if we end up url-encoding it (but still suggest we change it unless it's too much work).

2025-03-03 16:52 UTC, bjoerge commented on packages/sanity/src/core/releases/tool/components/Chip.tsx
> +} & Pick<CardProps, 'tone'>
nit: think I'd prefer `tone: CardProps['tone']` here over intersection type

2025-03-03 16:52 UTC, bjoerge commented on packages/sanity/src/core/util/draftUtils.ts
> +export function isSystemBundle(maybeSystemBundle: unknown): maybeSystemBundle is SystemBundle {
I like this name

2025-03-03 16:52 UTC, bjoerge commented on packages/sanity/src/structure/diffView/components/DiffView.tsx
> +        id="diffView"
Are we ok with this becoming a global id (and also a global variable), or should it be coming from useId()? Could lead to unpleasant surprises if we have multiple DiffView's on the page at the same time.

2025-03-03 16:52 UTC, bjoerge commented on packages/sanity/src/structure/diffView/hooks/useDiffViewRouter.ts
> +  } & Partial<
Would it be slightly more readable if options was typed `{mode?: DiffViewMode, previousDocument?: {type: string, id: string}}, nextDocument?: ?: {type: string, id: string}}`

2025-03-03 16:52 UTC, bjoerge commented on packages/sanity/src/structure/diffView/versionMode/components/VersionModeHeader.tsx
> +  {state: 'pending' | 'ready' | 'error'} & Pick<DocumentLayoutProps, 'documentId'>
(same comment as earlier re: intersection vs referencing to a type property)

2025-03-03 16:52 UTC, bjoerge commented on packages/sanity/src/structure/diffView/constants.ts
> +export const DIFF_SEARCH_PARAM_DELIMITER = ';'
Do we run this through encodeURIComponent? Since `;` is used to terminate various statements (sql, bash commands) etc, it's not uncommon for it to be blocked by various security middleware. If not too much work, I suggest we change to another delimiter.

2025-03-03 16:52 UTC, bjoerge commented on packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
> +  const filteredReleases = useFilteredReleases({displayed, documentId})
nice refactor!

2025-03-03 17:02 UTC, juice49 commented on packages/sanity/src/core/releases/tool/components/Chip.tsx
> +} & Pick<CardProps, 'tone'>
That's fair. I tend to prefer `pick` where I want the API to inherit an identical property name **and** value, as it more concretely establishes that relationship.

Worth thinking about, though. If you ever have a few mins for nerding out, I'd love to hear counterpoints on it 🙂.

2025-03-03 17:02 UTC, bjoerge commented on packages/sanity/src/structure/diffView/constants.ts
> +export const DIFF_SEARCH_PARAM_DELIMITER = ';'
For all we know middlewares might also block `%3B` because they know developers might as well decode that string befor passing it to system exec() 😅  Feels safer to replace with `‚` and I don't think that should be problematic here anyway as we don't allow that in either document types nor document ids(?). Maybe I'm being overly cautious…

2025-03-03 17:03 UTC, juice49 commented on packages/sanity/src/structure/diffView/components/DiffView.tsx
> +        id="diffView"
You're absolutely right. Thanks for pointing it out.

2025-03-03 17:09 UTC, bjoerge commented on packages/sanity/src/core/releases/tool/components/Chip.tsx
> +} & Pick<CardProps, 'tone'>
Good point, I didn't really consider the enforcing of both type and property name, I'm trending towards agreeing with you now 😄

2025-03-03 17:51 UTC, pedrobonamin approved these changes
This is great Ash, I've been trying it and it's a game changer for releases. Will make it very easy to compare two documents and even resolve differences because you got the option to edit them in place.
Thanks for building this huge piece!! 🙌🏻

2025-03-03 17:51 UTC, pedrobonamin commented on packages/sanity/src/core/form/useDocumentForm.ts
> +  releaseId?: string
Any reason this is changing? I know it's not ideal right now, given it is eventually an string, but if we later add the branded types I think it will make sense again.

2025-03-03 17:51 UTC, pedrobonamin commented on packages/sanity/src/core/perspective/PerspectiveProvider.tsx
> +      selectedReleaseId: isSystemBundleName(selectedPerspectiveName)
Is it possible to have here a `drafts` as `selectedPerspectiveName`? 
I think this could end going against we have been thinking in where the `drafts` is the undefined selectedPerspectiveName

2025-03-03 17:51 UTC, pedrobonamin commented on packages/sanity/src/core/util/draftUtils.ts
> +const systemBundleNames = ['draft', 'published'] as const
Curious on why we have `drafts` as systemBundles and `draft` as name, do we need the two? Could it be error prone to have two different strings that eventually means the same?

2025-03-03 17:51 UTC, pedrobonamin commented on packages/sanity/src/core/util/draftUtils.ts
> +const systemBundleNames = ['draft', 'published'] as const
Seeing your comment below, maybe we can update the uses of `draft` for `drafts` ? Do you have those identified? Not necessarily for this PR btw.

2025-03-03 17:51 UTC, pedrobonamin commented on packages/sanity/src/structure/diffView/components/DiffViewPane.tsx
> +  } = useDocumentForm({
🤩 I'm seeing some future simplifications to the `useDocumentForm` , the perspective and release id could be derived from the the document id if not provided.
so you could pass a raw document id and the hook handles the rest

2025-03-03 17:51 UTC, pedrobonamin commented on packages/sanity/src/structure/diffView/plugin/DiffViewDocumentLayout.tsx
> +export const DiffViewDocumentLayout: ComponentType<
nit: this is living now in a `/plugin` folder, maybe it should be part of `Components`?

2025-03-04 09:20 UTC, juice49 commented on packages/sanity/src/core/form/useDocumentForm.ts
> +  releaseId?: string
Apologies—I made this change while `ReleaseId` was still `r${string}` and marked as deprecated—I assumed any usage of `ReleaseId` was out of date.

I see it's now been changed to simply `string` with a todo to move it to `@sanity/id-utils`. I'll drop this commit! 🙂

2025-03-04 09:31 UTC, juice49 commented on packages/sanity/src/structure/diffView/constants.ts
> +export const DIFF_SEARCH_PARAM_DELIMITER = ';'
Very good points. Changed to `,` (`%2C`) 🙂.

https://github.com/sanity-io/sanity/blob/eb55bf407b2cc61c06707c7dd4394174bb7e02f5/packages/sanity/src/structure/diffView/constants.ts#L19

2025-03-04 09:36 UTC, juice49 commented on packages/sanity/src/core/form/useDocumentForm.ts
> +  releaseId?: string
Dropped ✅

2025-03-04 10:24 UTC, juice49 commented on packages/sanity/src/structure/diffView/components/DiffViewPane.tsx
> +  } = useDocumentForm({
Totally! I didn't want to refactor anything as this point, but I think there are improvements we can make. Thanks for making the reusable form happen 💖.

2025-03-04 10:25 UTC, juice49 commented on packages/sanity/src/structure/diffView/plugin/DiffViewDocumentLayout.tsx
> +export const DiffViewDocumentLayout: ComponentType<
You are right. A remnant of when this was actually a plugin 😔.

2025-03-04 10:28 UTC, juice49 commented on packages/sanity/src/core/util/draftUtils.ts
> +const systemBundleNames = ['draft', 'published'] as const
I agree that we should make this consistent, but I did not identify all the places it's used as part of this task.

2025-03-04 10:29 UTC, pedrobonamin commented on packages/sanity/src/core/util/draftUtils.ts
> +const systemBundleNames = ['draft', 'published'] as const
We can follow up on it, no need to block this

2025-03-04 12:06 UTC, juice49 commented on packages/sanity/src/core/perspective/PerspectiveProvider.tsx
> +      selectedReleaseId: isSystemBundleName(selectedPerspectiveName)
Hmm. If `selectedPerspectiveName` is `undefined`, then `selectedReleaseId` will resolve to `undefined`. If the intention is to view drafts, wouldn't it be correct that `selectedReleaseId` is `undefined`?

2025-03-04 13:08 UTC, bjoerge approved these changes
Awesome work, @juice49! 🚢

2025-03-04 13:08 UTC, merged